### PR TITLE
Update to 1.21.1

### LINKED ISSUE #298: Shader Parameter names swapped
**Minecraft version:** 1.21.1
**Mappings version:** 2024.07.28

`ShaderInstance.setDefaultUniforms` has 2nd (index 1) and 3rd (index 2) parameter swapped - a projection matrix is being bound in place of the model view matrix whilst the model view matrix is being bound in place of a projection matrix. For graphics developers, this creates a whimsically confusing visual bug

Screenshot 2024-08-12 at 9 45 17 AM

### PR DESCRIPTION
**Pull request by PiTheGuy**
Also updates enigma to 2.4.2

### CODE REVIEW

**Comment by eristhea** [comment]
changelogs: 
https://quiltmc.org/en/changelog/enigma/2.4.1/
https://quiltmc.org/en/changelog/enigma/2.4.2/

**Review by Matyrobbrt — APPROVED** [review]

**Comment by rlnt** [comment]
Is there something blocking this? It received approval over a month ago.

**Comment by gmitch215** [comment]
+1, any updates?

**Comment by PiTheGuy** [comment]
We are having issues with the backend code that validates incoming pull requests. The team is working to move it to GitHub Actions.

**Comment by HappyRespawnanchor** [comment]
Parchment seems to have stalled in Minecraft 1.21.0, will this pull request be merged in the future?

**Review by Lanse505 — APPROVED** [review]
LGTM

**Pull request merged**
