### PR TITLE
Update to 1.21.3

### PR DESCRIPTION
**Pull request by PiTheGuy**

### CODE REVIEW

**Comment by HappyRespawnanchor** [comment]
Parchment seems to have stalled in Minecraft 1.21.0, will this pull request be merged in the future?

**Comment by sciwhiz12** [comment]
Yes, we still plan to merge this PR (and the 1.21.1 PR first) in the future. We are currently stalled on moving our automations from the now-disabled LDTTeam TeamCity instance to GitHub Actions, which I admit is a bit reliant on me to do. 

Fortunately, my semestral final exams will be finished by the weekend, so I should be able to deal with all these within the next week. Thank you for your patience!

**Comment by gmitch215** [comment]
Any updates? 1.21.4 snapshots are out as well.

**Review by Lanse505 — COMMENTED** [review]
Reviewed 50% of this PR thus far, up until "SmoothDouble".
Everything looks good thus far.

**Review by Matyrobbrt — APPROVED** [review]

**Pull request merged**
